# -*- coding: utf-8 -*-
"""Payment History Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f4sJYXUt4FaYuAiox9yuL0S1IROS0mL9
"""

!pip install pandasql

import pandas as pd
from pandasql import sqldf

# 1. Load the uploaded file into a DataFrame
application = pd.read_csv('application_train.csv')
installment = pd.read_csv('installments_payments.csv')


# 2. Define a helpful function for running queries
pysqldf = lambda q: sqldf(q, globals())

# 3. Calculating Average_Number_late payment in days and number_of_late_payments
query = """
SELECT
    AVG(-DAYS_ENTRY_PAYMENT) AS AVERAGE_LATE_PAYMENTS, COUNT(DAYS_ENTRY_PAYMENT) AS num_late_payments
    FROM installment JOIN application ON installment.SK_ID_CURR = application.SK_ID_CURR
    WHERE DAYS_ENTRY_PAYMENT < 0;
"""
# Execute and view the results
result = pysqldf(query)
print(result)

#Comparison between late payment and no payment group's default rates
query = """
WITH loan_late_flag AS (
    SELECT
        SK_ID_CURR,
        MAX(CASE WHEN DAYS_ENTRY_PAYMENT < 0 THEN 1 ELSE 0 END) AS has_late_payment
    FROM installment
    GROUP BY SK_ID_CURR
)

SELECT
    CASE
        WHEN llf.has_late_payment = 1 THEN 'Has late payments'
        ELSE 'No late payments'
    END AS payment_status,
    ROUND(100.0 * SUM(app.TARGET) / COUNT(*), 2) AS default_rate,
    COUNT(*) AS total_loans,
    SUM(app.TARGET) AS total_defaults
FROM application app
LEFT JOIN loan_late_flag llf ON app.SK_ID_CURR = llf.SK_ID_CURR
GROUP BY llf.has_late_payment;
"""
# Execute and view the results
result = pysqldf(query)
print(result)

#Late Payment Metrics by Default Status:
query = """
WITH loan_late_metrics AS (
    SELECT
        SK_ID_CURR,
        COUNT(CASE WHEN DAYS_ENTRY_PAYMENT < 0 THEN 1 END) AS num_late_payments,
        AVG(CASE WHEN DAYS_ENTRY_PAYMENT < 0 THEN -DAYS_ENTRY_PAYMENT END) AS avg_days_late,
        MAX(CASE WHEN DAYS_ENTRY_PAYMENT < 0 THEN -DAYS_ENTRY_PAYMENT END) AS max_days_late
    FROM installment
    GROUP BY SK_ID_CURR
)

SELECT
    app.TARGET AS defaulted,
    COUNT(*) AS total_loans,
    ROUND(AVG(COALESCE(llm.num_late_payments, 0)), 2) AS avg_late_payments,
    ROUND(AVG(COALESCE(llm.avg_days_late, 0)), 2) AS avg_days_late,
    ROUND(MAX(COALESCE(llm.max_days_late, 0)), 2) AS max_days_late
FROM application app
LEFT JOIN loan_late_metrics llm ON app.SK_ID_CURR = llm.SK_ID_CURR
GROUP BY app.TARGET;
"""
# Execute and view the results
result = pysqldf(query)
print(result)

