# -*- coding: utf-8 -*-
"""Risk Dashboard Queries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SuBtJUDKK2ZDrP7nb406kpSFCIHKWVwR
"""

!pip install pandasql

import pandas as pd
from pandasql import sqldf

# 1. Load the uploaded file into a DataFrame
application = pd.read_csv('application_train.csv')
installment = pd.read_csv('installments_payments.csv')


# 2. Define a helpful function for running queries
pysqldf = lambda q: sqldf(q, globals())

# 3. Giving the overview of the whole dataset
query = """
SELECT
    COUNT(*) AS total_loans,
    SUM(TARGET) AS number_of_defaults,
    ROUND(100.0 * SUM(TARGET) / COUNT(*), 2) AS default_rate,
    ROUND(AVG(AMT_CREDIT),2) AS average_loan_amount,
    ROUND(AVG(AMT_INCOME_TOTAL),2) AS average_income
    FROM application

"""
# Execute and view the results
result = pysqldf(query)
print(result)

#showing the trend of defaults by age
query= """
SELECT
    CASE
        WHEN -DAYS_BIRTH / 365.0 BETWEEN 20 AND 30 THEN '20-30'
        WHEN -DAYS_BIRTH / 365.0 BETWEEN 31 AND 40 THEN '31-40'
        WHEN -DAYS_BIRTH / 365.0 BETWEEN 41 AND 50 THEN '41-50'
        ELSE '51+'
    END AS age_group,
    COUNT(*) AS total_loans,
    SUM(TARGET) AS total_defaults,
    ROUND(100.0 * SUM(TARGET) / COUNT(*), 2) AS default_rate
FROM application
WHERE DAYS_BIRTH IS NOT NULL
GROUP BY age_group
ORDER BY age_group;
"""
# Execute and view the results
result = pysqldf(query)
print(result)

#Query 3: Income × Age Risk GridPurpose: Show default rates across income and age segments (heatmap for dashboard)
query = """

SELECT
    CASE
        WHEN AMT_INCOME_TOTAL < 50000 THEN 'Low'
        WHEN AMT_INCOME_TOTAL BETWEEN 50000 AND 99999 THEN 'Medium'
        WHEN AMT_INCOME_TOTAL BETWEEN 100000 AND 149999 THEN 'High'
        ELSE 'Very High'
    END AS income_group,

    -- Age group: split into 4 age ranges using DAYS_BIRTH (converted to years)
    CASE
        WHEN -DAYS_BIRTH / 365.0 BETWEEN 18 AND 30 THEN 'Young'
        WHEN -DAYS_BIRTH / 365.0 BETWEEN 31 AND 40 THEN 'Mid'
        WHEN -DAYS_BIRTH / 365.0 BETWEEN 41 AND 50 THEN 'Mature'
        ELSE 'Senior'
    END AS age_group,

    -- Portfolio size in that segment
    COUNT(*) AS total_loans,

    -- Number of defaults in that segment
    SUM(TARGET) AS total_defaults,

    -- Default rate as a percentage (rounded to 2 decimals)
    ROUND(100.0 * SUM(TARGET) / COUNT(*), 2) AS default_rate

FROM application

-- Limit to realistic working age (18–70) to avoid outliers
WHERE -DAYS_BIRTH / 365.0 BETWEEN 18 AND 70

-- Group by both dimensions to create the grid
GROUP BY income_group, age_group

-- Sort so the grid is easy to read
ORDER BY income_group, age_group;
"""
# Execute and view the results
result = pysqldf(query)
print(result)

import sqlite3
import pandas as pd

# Connect to SQLite (creates a file-based DB)
conn = sqlite3.connect('credit_risk.db')

# Load CSVs and write to SQLite (do this once)
# If the DB already exists, skip this part
application = pd.read_csv('application_train.csv')
installment = pd.read_csv('installments_payments.csv')

application.to_sql('application', conn, if_exists='replace', index=False)
installment.to_sql('installment', conn, if_exists='replace', index=False)

# Now query directly from SQLite
query = """
WITH late_flag AS (
    SELECT
        SK_ID_CURR,
        MAX(CASE WHEN DAYS_ENTRY_PAYMENT < 0 THEN 1 ELSE 0 END) AS has_late_payment
    FROM installment
    GROUP BY SK_ID_CURR
),
age_calc AS (
    SELECT
        SK_ID_CURR,
        TARGET,
        AMT_INCOME_TOTAL,
        AMT_CREDIT,
        -DAYS_BIRTH / 365.0 AS age_years
    FROM application
)
SELECT
    a.SK_ID_CURR,
    a.AMT_INCOME_TOTAL AS income,
    a.AMT_CREDIT AS loan_amount,
    ROUND(a.age_years, 1) AS age,
    CASE
        WHEN l.has_late_payment = 1 THEN 'Yes'
        ELSE 'No'
    END AS has_late_payment,
    CASE
        WHEN a.AMT_INCOME_TOTAL < 40000 AND a.age_years < 30 THEN 'Yes'
        WHEN a.AMT_CREDIT > 150000 THEN 'Yes'
        WHEN l.has_late_payment = 1 THEN 'Yes'
        ELSE 'No'
    END AS high_risk_flag
FROM age_calc a
LEFT JOIN late_flag l ON a.SK_ID_CURR = l.SK_ID_CURR
WHERE a.age_years BETWEEN 18 AND 70
ORDER BY high_risk_flag DESC, a.SK_ID_CURR
"""

# Run query directly from SQLite
result = pd.read_sql(query, conn)

# Save to CSV
result.to_csv('high_risk.csv', index=False)

import sqlite3
import pandas as pd

# Connect to SQLite database (creates a file on disk)
conn = sqlite3.connect('credit_risk.db')

# Load CSVs into SQLite (do this once)
# If you've already done this, skip the next two lines
application = pd.read_csv('application_train.csv')
installment = pd.read_csv('installments_payments.csv')

application.to_sql('application', conn, if_exists='replace', index=False)
installment.to_sql('installment', conn, if_exists='replace', index=False)

# Now run the query from SQLite — no RAM overload
query = """
WITH late_flag AS (
    SELECT
        SK_ID_CURR,
        MAX(CASE WHEN DAYS_ENTRY_PAYMENT < 0 THEN 1 ELSE 0 END) AS has_late_payment
    FROM installment
    GROUP BY SK_ID_CURR
)
SELECT COUNT(*)
FROM application a
LEFT JOIN late_flag l ON a.SK_ID_CURR = l.SK_ID_CURR;
"""

result = pd.read_sql(query, conn)
print(result)

import sqlite3
import pandas as pd

conn = sqlite3.connect('credit_risk.db')

query = """
WITH loan_late_flag AS (
    SELECT
        SK_ID_CURR,
        MAX(CASE WHEN DAYS_ENTRY_PAYMENT < 0 THEN 1 ELSE 0 END) AS has_late_payment
    FROM installment
    GROUP BY SK_ID_CURR
)
SELECT
    CASE
        WHEN llf.has_late_payment = 1 THEN 'Has late payments'
        ELSE 'No late payments'
    END AS payment_status,
    COUNT(*) AS total_loans,
    SUM(app.TARGET) AS total_defaults,
    ROUND(100.0 * SUM(app.TARGET) / COUNT(*), 2) AS default_rate
FROM application app
LEFT JOIN loan_late_flag llf ON app.SK_ID_CURR = llf.SK_ID_CURR
GROUP BY llf.has_late_payment;
"""

result = pd.read_sql(query, conn)
result.to_csv('payment_history_analysis.csv', index=False)
print(result)