# -*- coding: utf-8 -*-
"""Loan Portfolio Summary

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U7qDJ7y7vDJfyLXW_03QG40PwwBcaMrb
"""

!pip install pandasql

import pandas as pd
from pandasql import sqldf

# 1. Load the uploaded file into a DataFrame
df = pd.read_csv('application_train.csv')

# 2. Define a helpful function for running queries
pysqldf = lambda q: sqldf(q, globals())

# 3. Write the SQL query Impact of income level on defaulting
query = """
SELECT
    CASE
        WHEN AMT_INCOME_TOTAL < 50000 THEN 'Low'
        WHEN AMT_INCOME_TOTAL < 100000 THEN 'Medium'
        ELSE 'High'
    END AS income_bracket,
    COUNT(*) AS total_loans,
    SUM(TARGET) AS total_defaults,
    ROUND(100.0 * SUM(TARGET) / COUNT(*), 2) AS default_rate
FROM df
GROUP BY income_bracket
ORDER BY income_bracket;
"""

# Execute and view the results
result = pysqldf(query)
print(result)

#Impact on average loan size on default rate
pysqldf = lambda q: sqldf(q, globals())
query = """
SELECT target, AVG(AMT_CREDIT) AS avg_loan_amount
FROM df
GROUP BY target
"""

#Execute and view the results
result = pysqldf(query)
print(result)

#Impact of contract type on default rate
query = """
SELECT NAME_CONTRACT_TYPE, COUNT(*) AS total_loans,
    SUM(TARGET) AS total_defaults,
    ROUND(100.0 * SUM(TARGET) / COUNT(*), 2) AS default_rate
FROM df
GROUP BY NAME_CONTRACT_TYPE
"""

# Execute and view the results
result = pysqldf(query)
print(result)

#Impact of age on default rate
query = """
SELECT
    CASE
        WHEN -DAYS_BIRTH / 365.0 BETWEEN 20 AND 30  THEN 'Young'
        WHEN -DAYS_BIRTH / 365.0 BETWEEN 31 AND 40  THEN 'Middle-aged'
        WHEN -DAYS_BIRTH / 365.0 BETWEEN 41 AND 50  THEN 'Mature'
        ELSE 'Senoir'
    END AS Age,
    COUNT(*) AS total_loans,
    SUM(TARGET) AS total_defaults,
    ROUND(100.0 * SUM(TARGET) / COUNT(*), 2) AS default_rate
FROM df
GROUP BY Age
ORDER BY Age;
"""

#Execute and view the results
result = pysqldf(query)
print(result)

#Impact of gender on default rate
query = """
SELECT
    CODE_GENDER,
    COUNT(*) AS total_loans,
    SUM(TARGET) AS total_defaults,
    ROUND(100.0 * SUM(TARGET) / COUNT(*), 2) AS default_rate
FROM df
WHERE CODE_GENDER IN ('M', 'F')
GROUP BY CODE_GENDER
ORDER BY default_rate DESC;
"""
#Execute and view the results
result = pysqldf(query)
print(result)

#Whether having children affects default rates
query = """
SELECT
    CASE
        WHEN CNT_CHILDREN > 0  THEN 'With_Children'
        ELSE 'No_Children'
    END AS Children_Number,
    COUNT(*) AS total_loans,
    SUM(TARGET) AS total_defaults,
    ROUND(100.0 * SUM(TARGET) / COUNT(*), 2) AS default_rate
FROM df
GROUP BY Children_Number
ORDER BY default_rate DESC;
"""
#Execute and view the results
result = pysqldf(query)
print(result)